name: 'rwe_dbt'
version: '1.0.0'
config-version: 2

profile: 'rwe_dbt'

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  rwe_dbt:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
